# Generated by Django 5.1.2 on 2024-10-15 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='oauth_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oauth_provider',
        ),
    ]
